In [1]:
import numpy as np
import tensorflow as tf
from adult_modified import preprocess_adult_data
from sklearn import linear_model
import model
import utils
import time
import multiprocessing as mp
import random
import matplotlib.pyplot as plt
import scipy
plt.ioff()


seed = 1
tf.random.set_seed(seed)
np.random.seed(seed)
dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = seed)

x_unprotected_train, x_protected_train = dataset_orig_train.features[:, :39], dataset_orig_train.features[:, 39:]
x_unprotected_test, x_protected_test = dataset_orig_test.features[:, :39], dataset_orig_test.features[:, 39:]
y_train, y_test = dataset_orig_train.labels.reshape((-1,)), dataset_orig_test.labels.reshape((-1,))


# Casing to tensor 
#y_train, y_test = y_train.astype('int32'), y_test.astype('int32')
x_unprotected_train, x_unprotected_test = tf.cast(x_unprotected_train, dtype = tf.float32), tf.cast(x_unprotected_test, dtype = tf.float32)
#y_train, y_test = tf.one_hot(y_train, 2), tf.one_hot(y_test, 2)




graph = model.model   
prob = graph(x_unprotected_test)
y_pred = tf.argmax(prob, axis = 1)
y_pred = y_pred.numpy()

In [2]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [3]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

In [4]:
dataset_orig_test

               instance weights  features                             \
                                                                       
                                      age education-num capital-gain   
instance names                                                         
13237                       1.0 -1.175586     -1.607059    -0.147413   
23644                       1.0  0.264770     -0.435784    -0.147413   
178                         1.0 -1.554628     -0.435784    -0.147413   
16741                       1.0 -0.341696     -0.435784    -0.147413   
28620                       1.0 -0.948162     -0.435784    -0.147413   
...                         ...       ...           ...          ...   
47211                       1.0 -1.099778      1.125916    -0.147413   
35106                       1.0  0.264770      1.125916    -0.147413   
5661                        1.0 -1.478820     -2.387908    -0.147413   
13155                       1.0 -1.630436     -1.607059    -0.14

In [10]:
gender = dataset_orig_test.features[:, 39]
race = dataset_orig_test.features[:, 40]

In [11]:
gender

array([1., 1., 1., ..., 1., 0., 0.])

In [1]:
import numpy as np
np.random.seed(1)
# Adult data processing
seeds = np.random.randint(100000, size = (10, ))

NameError: name 'np' is not defined