In [12]:
import tensorflow as tf
from tensorflow import keras
import json
import numpy as np

In [13]:
with open('data.txt', 'r') as f:
    weight = json.load(f)

In [14]:
weights = [np.array(w) for w in weight]

In [9]:
x = tf.cast(np.random.normal(size=(100, 39)), dtype = tf.float32)

In [11]:
len(weights[0][0])

100

In [16]:
for w in weights:
    print(w.shape)

(39, 100)
(100,)
(100, 2)
(2,)


In [20]:
a = keras.layers.Layer(100)

In [21]:
a.set_weights([weights[0], weights[1]])

ValueError: You called `set_weights(weights)` on layer "layer" with a weight list of length 2, but the layer was expecting 0 weights. Provided weights: [array([[ 0.00319816,  0.06832858, -0.11650787, .....

In [22]:
import model

In [23]:
graph = model.model

In [24]:
graph(x)

<tf.Tensor: shape=(100, 2), dtype=float32, numpy=
array([[0.09334087, 0.9066591 ],
       [0.4064124 , 0.5935876 ],
       [0.9623238 , 0.03767623],
       [0.0488424 , 0.9511576 ],
       [0.712958  , 0.28704196],
       [0.37976164, 0.62023836],
       [0.7567461 , 0.24325383],
       [0.69366044, 0.30633953],
       [0.7201703 , 0.27982968],
       [0.08202656, 0.9179734 ],
       [0.62318665, 0.37681332],
       [0.81327266, 0.18672734],
       [0.33628353, 0.66371644],
       [0.90280396, 0.09719604],
       [0.77634513, 0.2236549 ],
       [0.9490829 , 0.05091712],
       [0.1436861 , 0.85631394],
       [0.3305564 , 0.6694436 ],
       [0.65772754, 0.34227243],
       [0.0239623 , 0.97603774],
       [0.8297616 , 0.17023842],
       [0.776974  , 0.223026  ],
       [0.7687033 , 0.23129676],
       [0.8164722 , 0.18352789],
       [0.5989719 , 0.4010281 ],
       [0.23860756, 0.7613925 ],
       [0.572567  , 0.42743298],
       [0.2554722 , 0.7445278 ],
       [0.21443102, 0.7855

In [4]:
import numpy as np
import tensorflow as tf
from adult_modified import preprocess_adult_data
from sklearn import linear_model
import model
import utils
import time
import multiprocessing as mp
import random
import matplotlib.pyplot as plt
import scipy
plt.ioff()


seed = 1
tf.random.set_seed(seed)
np.random.seed(seed)
dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = seed)

x_unprotected_train, x_protected_train = dataset_orig_train.features[:, :39], dataset_orig_train.features[:, 39:]
x_unprotected_test, x_protected_test = dataset_orig_test.features[:, :39], dataset_orig_test.features[:, 39:]
y_train, y_test = dataset_orig_train.labels.reshape((-1,)), dataset_orig_test.labels.reshape((-1,))

In [5]:
sensetive_directions = []
protected_regression = linear_model.LogisticRegression(fit_intercept = True)
protected_regression.fit(x_unprotected_train, x_protected_train[:, 0])
sensetive_directions.append(protected_regression.coef_.reshape((-1,)))
protected_regression.fit(x_unprotected_train, x_protected_train[:, 1])
sensetive_directions.append(protected_regression.coef_.reshape((-1,)))
sensetive_directions = np.array(sensetive_directions)

In [6]:
sensetive_directions.shape

(2, 39)

In [1]:
import numpy as np
a = np.load('outcome/perturbed_ratio_l2_base.npy')

In [2]:
a

array([1.0019885, 1.0015621, 1.0250211, ..., 1.0055652, 1.0033357,
       1.003548 ], dtype=float32)

In [4]:
np.mean(a)

1.0336033

In [7]:
np.sqrt(a.shape[0])*(np.mean(a)-1)/np.std(a)

82.7292715625518

In [1]:
import numpy as np
a = np.load('outcome/perturbed_ratio.npy')

In [2]:
a

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)