In [5]:
import tensorflow as tf
import numpy as np
a = tf.cast([1, 2], dtype = tf.float32)
a = tf.reshape(a, (-1, 1))

In [6]:
x = tf.cast(np.random.normal(size=(10, 2)), dtype=tf.float32)


In [13]:
logits = x @ a
probs = tf.exp(logits) / (1 + tf.exp(logits))

In [14]:
tf.concat([probs, 1-probs], axis= 1)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0.02894572, 0.97105426],
       [0.7119273 , 0.2880727 ],
       [0.11801468, 0.8819853 ],
       [0.8809856 , 0.11901438],
       [0.4200891 , 0.5799109 ],
       [0.3149579 , 0.68504214],
       [0.3377741 , 0.6622259 ],
       [0.84252274, 0.15747726],
       [0.21136895, 0.7886311 ],
       [0.7473265 , 0.2526735 ]], dtype=float32)>

In [15]:
probs

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.02894572],
       [0.7119273 ],
       [0.11801468],
       [0.8809856 ],
       [0.4200891 ],
       [0.3149579 ],
       [0.3377741 ],
       [0.84252274],
       [0.21136895],
       [0.7473265 ]], dtype=float32)>

In [16]:
logits

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-3.51296   ],
       [ 0.90476286],
       [-2.0113664 ],
       [ 2.0017962 ],
       [-0.32240772],
       [-0.77704144],
       [-0.6732295 ],
       [ 1.6771199 ],
       [-1.3166933 ],
       [ 1.0844039 ]], dtype=float32)>

In [17]:
x 

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[ 0.2693168 , -1.8911383 ],
       [ 0.9198729 , -0.00755502],
       [-0.34966707, -0.8308497 ],
       [ 0.3362664 ,  0.83276486],
       [ 1.4953445 , -0.9088761 ],
       [-0.30576265, -0.2356394 ],
       [ 0.06781466, -0.37052208],
       [ 1.2065172 ,  0.23530132],
       [-0.7051262 , -0.30578354],
       [ 1.0179478 ,  0.03322802]], dtype=float32)>

In [18]:
tf.norm(x, axis = 1)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.9102187 , 0.919904  , 0.9014312 , 0.8980937 , 1.7498889 ,
       0.38602683, 0.37667686, 1.2292479 , 0.76857436, 1.01849   ],
      dtype=float32)>

In [1]:
import generate_data
generate_data.get_data()


In [1]:
import loss_ratio
import numpy as np
import tensorflow as tf
#loss_ratio.mean_ratio([1, 1], [1, 1], num_steps=10)

In [30]:
theta = [2, 1]
fair_direction = [0, 1]
x, y = np.load('data/x.npy'), np.load('data/y.npy')
x, y = tf.cast(x, dtype = tf.float32), y.astype('int32')


In [31]:
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1], dtype=int32)

In [32]:
y = tf.one_hot(y, 2)

cl = loss_ratio.linear_classifier(theta)
while np.linalg.norm(fair_direction) != 1:
    fair_direction = fair_direction / np.linalg.norm(fair_direction)
fair_metric = loss_ratio.fair_metric_fn(fair_direction)
    

In [33]:
ratios = []
for u, v in zip(x, y):
    r = loss_ratio.sample_perturbation(u, v, classifier  = cl, fair_metric = fair_metric, regularizer=1,\
             learning_rate=1e-1, num_steps=20)

    ratios.append(r)

In [34]:
ratios

[5.388805,
 6.5487447,
 3.5338683,
 5.4728065,
 3.9226549,
 4.15661,
 1.3181529,
 4.3235846,
 3.3196394,
 3.5003037,
 2.5632374,
 3.0338843,
 4.295245,
 3.332169,
 1.6346368,
 4.546305,
 1.1574323,
 1.2603699,
 1.1783159,
 7.028069,
 3.30501,
 1.7399428,
 1.9709316,
 9.382542,
 2.2909553,
 3.8592067,
 1.1249493,
 1.7234528,
 2.9659655,
 3.2529333,
 1.5300139,
 4.0862727,
 4.1763897,
 6.6450133,
 5.711625,
 1.0828496,
 2.8027472,
 3.2697089,
 3.6662154,
 2.8525994,
 1.4068408,
 2.205729,
 3.9820764,
 2.4275181,
 3.279062,
 5.3404183,
 3.270184,
 3.4142158,
 1.4071885,
 1.4357408,
 1.8207332,
 4.4621887,
 1.1762613,
 3.5488336,
 1.4482366,
 1.1398406,
 4.14023,
 3.5195277,
 3.1848614,
 5.4022293,
 3.4463553,
 7.7291164,
 1.1360991,
 6.403283,
 1.2337675,
 2.4302738,
 1.1878355,
 4.2089143,
 3.7109354,
 4.621941,
 1.4558392,
 5.257373,
 4.340317,
 2.1957653,
 2.7139707,
 2.8667812,
 15.065415,
 4.114224,
 1.4823084,
 2.6119747,
 5.894078,
 3.8384826,
 3.4486473,
 3.0598927,
 5.2546606,
 1

In [15]:
u, v = x[0], y[0]

In [16]:
classifier = cl

In [21]:
import utils
x = tf.reshape(u, (1, -1))
y = tf.reshape(v, (1, -1))
x_start = x
x_fair = x
num_steps, regularizer, learning_rate = 20, 5, 1e-3
    #x += tf.cast(np.random.normal(size=(1, 39)), dtype = tf.float32)*1e-9
for _ in range(num_steps):
    with tf.GradientTape() as g:
        g.watch(x_fair)
        prob = classifier(x_fair)
        loss = utils.EntropyLoss(y, prob)  - regularizer * tf.reduce_sum(fair_metric(x_fair - x_start)**2)
        print(loss)

    gradient = g.gradient(loss, x_fair)
    x_fair = x_fair + learning_rate * gradient#utils.protected_direction(gradient, sensetive_directions)
    print(gradient)

ratio = utils.EntropyLoss(y, classifier(x_fair)) / utils.EntropyLoss(y, classifier(x_start))

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [20]:
ratio

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [22]:
u, v

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.6878273, -0.3058782], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>)

In [48]:
import itertools
theta1 = np.arange(0, 5, step = 0.2)
theta2 = np.arange(0, 5, step= 0.2)
a = itertools.product(theta1, theta2)

In [49]:
b = [list(i) for i in a]

In [50]:
b[0]

[0.0, 0.0]

In [52]:
f = lambda a, b, c : a+b+c
from functools import partial
g = partial(f, b= 2, c= 3)

In [54]:
g(3)

8